name: Build and deploy

on:
  push:
    branches: ['main']
    paths: ['index.html', 'package.json', 'vite.config.ts', '.github/workflows/publish.yml', 'public/**', 'src/**']
  workflow_dispatch:

concurrency:
  group: 'dist'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    steps:
      - name: Configure git
        run: |
          cd ${{ github.workspace }}
          git init
          git config core.symlinks true
          git config core.longpaths true
          cd -

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        deployments: write
      needs: build
      steps:
        - name: Download dist artifact
          uses: actions/download-artifact@v4
          with:
            name: dist
            path: dist

        - name: Deploy
          uses: cloudflare/wrangler-action@v3
          with:
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            command: pages deploy dist --project-name=greatsphynx-chat-archive
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
            wranglerVersion: latest
